apiVersion: v1
kind: Service
metadata:
  labels:
    app: starter-app
  name: demo-tenant-starter-app
  namespace: demo-tenant
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: starter-app
  type: LoadBalancer